# Generated by Django 4.0.1 on 2023-01-16 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='T_Dossier',
            fields=[
                ('Dossier_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Dossier_Name', models.CharField(max_length=100, unique=True)),
                ('Dossier_Parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Dossier.t_dossier')),
            ],
        ),
    ]
