# Generated by Django 4.0.1 on 2023-01-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0002_t_rectangle'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_RectField',
            fields=[
                ('Field_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Field_Name', models.CharField(max_length=100, unique=True)),
                ('Rect_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.t_rectangle')),
            ],
        ),
    ]
