# Generated by Django 4.0.1 on 2023-02-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0003_t_rectfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Rect',
            fields=[
                ('R_Id', models.AutoField(primary_key=True, serialize=False)),
                ('R_Name', models.CharField(max_length=100, unique=True)),
                ('Dossier_Id', models.ManyToManyField(to='Dossier.T_Dossier')),
            ],
        ),
    ]
