# Generated by Django 4.0.1 on 2023-02-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0004_t_rect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_dossier',
            name='Dossier_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='t_rect',
            name='R_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='t_rectangle',
            name='Rect_Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='t_rectfield',
            name='Field_Name',
            field=models.CharField(max_length=100),
        ),
    ]
