# Generated by Django 4.0.1 on 2023-02-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0005_alter_t_dossier_dossier_name_alter_t_rect_r_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Field',
            fields=[
                ('Field_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Field_Name', models.CharField(max_length=100)),
                ('Rect_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dossier.t_rect')),
            ],
        ),
    ]
