# Generated by Django 4.0.1 on 2023-03-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0006_t_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_field',
            name='Dossier_Id',
            field=models.ManyToManyField(to='Dossier.T_Dossier'),
        ),
    ]
