# Generated by Django 4.0.1 on 2023-03-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0007_t_field_dossier_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
