# Generated by Django 4.0.1 on 2023-03-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0009_t_link_delete_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_rectfield',
            name='Rect_Id',
        ),
        migrations.DeleteModel(
            name='T_Rectangle',
        ),
        migrations.DeleteModel(
            name='T_RectField',
        ),
    ]
