# Generated by Django 4.0.1 on 2023-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dossier', '0010_remove_t_rectfield_rect_id_delete_t_rectangle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_link',
            name='Dossier_Id',
            field=models.ManyToManyField(to='Dossier.T_Dossier'),
        ),
    ]
